name:                regex-equality
version:             0.1.0.0
github:              "githubuser/regex-equality"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/regex-equality#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.11
- mtl
- multimap
- hspec
- parsec
- warp
- wai
- wai-extra
- http-types
- binary
- bytestring

library:
  source-dirs: src

executables:
  regex-equality-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-equality

tests:
  regex-equality-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-equality
